language: node_js
node_js:
  - "4.4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - uuid-dev
    - build-essential
    - qemu-utils
install:
  - npm install
  - wget https://github.com/rubiojr/vhd-util-convert/archive/master.tar.gz -O /tmp/vhd-util-convert.tar.gz
  - tar -xvf /tmp/vhd-util-convert.tar.gz
  - (cd vhd-util-convert-master && make)
script:
  - npm test
