language: node_js
node_js:
  - "4.4"
addons:
  apt:
    packages:
      - uuid-dev
      - build-essential
install:
  - npm install
  - wget https://github.com/rubiojr/vhd-util-convert/archive/master.tar.gz -O /tmp/vhd-util-convert.tar.gz
  - tar -xvf /tmp/vhd-util-convert.tar.gz
  - cd vhd-util-convert-master && make
script:
  - npm test
